name: Build Project

on:
  push:
    branches: [ "main" ]

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: github-build-${{ github.run_number }}
          release_name: Build ${{ github.run_number }}
          body: Build for run \#${{ github.run_number }}
          draft: false
          prerelease: true